networks:
  pulsetracker-network:
services:
  soketi: 
    restart: unless-stopped
    image: quay.io/soketi/soketi:1.4-16-debian
    environment:
      SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
      SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
      SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
    networks:
      - pulsetracker-network
  mariadb:
    restart: unless-stopped
    build: ./mariadbBuild
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: pulse_tracker
    ports: 
      - 3301:3306
    networks:
      - pulsetracker-network
  redis:
    restart: unless-stopped
    image: bitnami/redis:6.2.14
    volumes:
      - ./redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PWD}
    networks:
      - pulsetracker-network
    ports: 
      - 6379:6379
  php:
    restart: unless-stopped
    image: ghcr.io/serversideup/php:8.3-fpm-nginx
    volumes: 
     - ./src:/var/www/html
     - ./nginx/:/etc/nginx/conf.d/:ro
    ports: 
      - 83:8443
      - 6001:6001
    environment:
      SSL_MODE: "mixed"
      SSL_PRIVATE_KEY_FILE: "/etc/ssl/private/test-key.pem"
      SSL_CERTIFICATE_FILE: "/etc/ssl/private/test.pem"
    networks:
      - pulsetracker-network
  queue:
    restart: unless-stopped
    image: ghcr.io/serversideup/php:8.3-fpm-nginx
    volumes: 
     - ./src:/var/www/html
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    environment:
      PHP_FPM_POOL_NAME: "pulse-queue"
    networks:
      - pulsetracker-network
    deploy:
      mode: replicated
      replicas: 6
    depends_on:
      - redis
      - mariadb
      - soketi
      - php
  geoqueue:
    restart: unless-stopped
    image: ghcr.io/serversideup/php:8.3-fpm-nginx
    volumes: 
     - ./src:/var/www/html
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3", "--queue=geopulse"]
    environment:
      PHP_FPM_POOL_NAME: "pulse-queue"
    depends_on:
      - redis
      - mariadb
      - soketi
      - php
    networks:
      - pulsetracker-network
    deploy:
      mode: replicated
      replicas: 6
  geopulse:
    restart: unless-stopped
    deploy:
     resources:
      limits:
        memory: 2048M
    build: ./geopulse
    environment:
      DISABLE_DEFAULT_SERVER: 1
    volumes:
      - ./geopulse/src/:/var/www/html/
    networks:
      - pulsetracker-network
    ports:
      - "9505:9505/udp"